[local]
localhost

[mongodb]
mongodb.daws89s.fun

[redis]
redis.daws89s.fun

[mysql]
mysql.daws89s.fun

[rabbitmq]
rabbitmq.daws89s.fun

[catalogue]
catalogue.daws89s.fun

[cart]
cart.daws89s.fun

[user]
user.daws89s.fun

[shipping]
shipping.daws89s.fun

[payment]
payment.daws89s.fun

[frontend]
frontend.daws89s.fun

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321